// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisitorDetails.Data;

namespace VisitorDetails.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VisitorDetails.Models.PurposeOfVisit", b =>
                {
                    b.Property<int>("PurposeOfVisitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("PurposeOfVisitID");

                    b.ToTable("VIS_PurposeOfVisit");
                });

            modelBuilder.Entity("VisitorDetails.Models.Site", b =>
                {
                    b.Property<string>("SiteCode")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("SiteEncryptedCode")
                        .HasColumnType("nvarchar(36)")
                        .HasMaxLength(36);

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("SiteCode");

                    b.ToTable("Site");
                });

            modelBuilder.Entity("VisitorDetails.Models.SystemSetting", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SystemSetting");
                });

            modelBuilder.Entity("VisitorDetails.Models.Visitor", b =>
                {
                    b.Property<int>("VisitorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(45)")
                        .HasMaxLength(45);

                    b.Property<DateTime?>("LeaveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MobileOptOut")
                        .HasColumnType("bit");

                    b.Property<string>("MobileTel")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<int?>("NumberOfGuests")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("PurposeOfVisitID")
                        .HasColumnType("int");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("SiteCode1")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitorID");

                    b.HasIndex("PurposeOfVisitID");

                    b.HasIndex("SiteCode1");

                    b.ToTable("VIS_Visitor");
                });

            modelBuilder.Entity("VisitorDetails.Models.Visitor", b =>
                {
                    b.HasOne("VisitorDetails.Models.PurposeOfVisit", "PurposeOfVisit")
                        .WithMany()
                        .HasForeignKey("PurposeOfVisitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VisitorDetails.Models.Site", "Site")
                        .WithMany("Visitor")
                        .HasForeignKey("SiteCode1");
                });
#pragma warning restore 612, 618
        }
    }
}
